name: Update Kaggle Dataset

on:
  schedule:
    - cron: '0 12 * * 1'  # Cotygodniowa aktualizacja (poniedziałek o 12:00 UTC)
  workflow_dispatch:  # Możliwość ręcznego uruchomienia w GitHub Actions

jobs:
  update_dataset:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libxml2 libxslt1-dev

      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      - name: Install dependencies
        run: pip install -r scraper/requirements.txt

      - name: Set Kaggle API credentials
        run: |
          mkdir -p ~/.kaggle
          echo "{\"username\":\"$KAGGLE_USERNAME\",\"key\":\"$KAGGLE_KEY\"}" > ~/.kaggle/kaggle.json
          chmod 600 ~/.kaggle/kaggle.json
        env:
          KAGGLE_USERNAME: ${{ secrets.KAGGLE_USERNAME }}
          KAGGLE_KEY: ${{ secrets.KAGGLE_KEY }}

      - name: Run scraper script
        run: python scraper/scraper.py
